spring:
  datasource:
    url: jdbc:h2:mem:project;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # Доступ к консоли /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use_sql_comments: true

admin:
  password: ${ADMIN_PASSWORD:password123}