spring:
  datasource:
    url: jdbc:h2:mem:project;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    # ОТКЛЮЧЕНО, чтобы не мешать дебагу
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    jwt:
      secret: "yourVeryLongAndRandomSecretKeyHere1234567890ABCDEF1234567890GHIJKLMNOP"
      expiration: 3600000
admin:
  password: ${ADMIN_PASSWORD:password123}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    # Полностью выключаем логи Hibernate для чистоты
    org.hibernate.SQL: ERROR
    org.hibernate.orm.results: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    # Глушим варнинги JWT
    # hexlet.code.config.JwtRequestFilter: ERROR