spring:
  datasource:
    # Используем стандартные переменные, которые часто дают облачные хостинги
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false # В продакшене логи забивать не нужно
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Консоль H2 в продакшене должна быть строго выключена (по умолчанию так и есть)
  h2:
    console:
      enabled: false

# В продакшене пароль админа ОБЯЗАТЕЛЬНО должен быть в переменной
admin:
  password: ${ADMIN_PASSWORD}